### ISSUE TITLE
Language on browser

### ISSUE THREAD

**Issue by amisha2016** [giggls/mapnik-german-l10n#5]
I am trying to change the language of my own OSM tile server from English to my language i.e. Hindi. I have followed the steps as you explained in your repo. I am able to see all the changes in my database. I am not able to see the word "भारत" to the map on browser shown [here](http://i.imgur.com/Qyzawpj.png).

One more doubt I am having is on entering the centroid point of India I am not getting country code"in".

```
gis=# select osml10n_get_country(ST_GeomFromText('POINT(82 21)', 4326));
 osml10n_get_country 
---------------------
 
(1 row)
```

Operating System- Ubuntu 14.04 LTS 
Thanks in advance for your help

**Comment by giggls** [comment]
This code is designed for target languages written in latin alphabet in mind. Thus it may well behave in strange ways using target languages like hindi which are not written in latin!

Have a look at my presentation from FOSS4G linked in the wiki to see what this is all about.
https://github.com/giggls/mapnik-german-l10n/wiki

You might probably be better off using COALESCE function instead of my code:
SELECT COALESCE(tags->'name:hi',tags->'name:en',name) from ...

This works for me:
SELECT COALESCE(tags->'name:hi',tags->'name:en',name) from planet_osm_point where osm_id=537966705;

Concerning your osml10n_get_country function (which is currently used only for determination of which transliteration mechanism to use) it looks like the India polygon in country_osm_grid might be broken. This is taken verbatim from nominatim. I just submitted a bug there:
https://github.com/twain47/Nominatim/issues/616

**Comment by giggls** [comment]
A second comment. I forgot to mention, that I would of course be happy to help making this code usable for non latin language targets. Make shure to watch the video, then we might be able to define the naming conventions for a hindi language map afterwards.

**Comment by amisha2016** [comment]
@giggls Thanks for your reply
I have tried COALESCE function also but problem not solved. I am able to see the output in my database but not to the map in browser.

```
gis=# SELECT COALESCE(tags->'name:hi',tags->'name:en',name) from planet_osm_polygon where name='India';
 coalesce 
----------
 त
(1 row)
```
Map on browser

![i](https://cloud.githubusercontent.com/assets/17342222/22512072/c4eafe9a-e8bd-11e6-96ae-40b1e78da9c4.png)

I am confuse that whether it is the problem of  the module mod_tile or postrgesql only.

I would also be happy to do the task with you.

**Comment by giggls** [comment]
To see the output in the map the renderer Software has to use the correct database queries.
E.g. in Geman style I use database views providing "columns" called  localized_name_second and such.
See https://github.com/giggls/openstreetmap-carto-de/tree/master/views_osmde

E.g. a style has to use something like "select COALESCE(tags->'name:hi',tags->'name:en',name) as name from ..." instead of just using "select name from ...".

I recommend using views as well. This way you can "redirect" selections of "name" column in standard style to a localized form of name using COALESCE or one of my functions provided here.

**Comment by amisha2016** [comment]
I think I have done in the same way as you explained above but forgot to mention here. I have changed the command in the file OSMBright.xml to  "select COALESCE(tags->'name:hi',tags->'name:en',name) as name ..." and as I said above I succeeded in viewing the map in browser in latin languages but not in my own language.

**Comment by giggls** [comment]
It just tried the naive approach of changing the 'de' to 'hi' in the views mentioned above. Even this seems to mostly work (see attached screenshot from kosmtik) As I already said I recommend using views.
![foo](https://cloud.githubusercontent.com/assets/7996314/22626945/4e470c36-ebb8-11e6-80e7-466ab3a6c13c.png)

**Comment by amisha2016** [comment]
I am unable to understand that why I have to create view if I have relation with the same name. Should I have to clone the repo [https://github.com/giggls/openstreetmap-carto-de](url). 
The overall changes I have doone is shown below.
Changes in relation planet_osm_polygon

![pla](https://cloud.githubusercontent.com/assets/17342222/22627606/05b10f9c-ebec-11e6-9228-a63d4d82df76.png)

Changes in OSMBright.xml

![osm](https://cloud.githubusercontent.com/assets/17342222/22627627/533be3a4-ebec-11e6-8d97-2bf29098371d.png)

May be I am doing some silly mistake in your perspective.

**Comment by giggls** [comment]
Hm OSMBright is vector tiles, right? I am not yet very familiar with vector tiles. This said: When using vector tiles you have to re-create them after changing an SQL query.

**Comment by Bibi56** [comment]
The issue seems to be a font issue, as the letters are replaced by squares. Be sure the selected font supports Indi characters.

@giggls, with Tessera (for instance) you can deliver vector tiles or bitmap tiles from the same source (PostGres/PostGIS, shapefiles, ...) using Mapnik for server rendering or delivering MVT for client rendering.
